server {
  listen 80;
  location /api/v1/auth/ { proxy_pass http://auth:8000/api/v1/auth/; include /etc/nginx/proxy_params; }
  location /api/v1/customers/ { proxy_pass http://customer:8000/api/v1/customers/; include /etc/nginx/proxy_params; }
  location /api/v1/accounts/ { proxy_pass http://account:8000/api/v1/accounts/; include /etc/nginx/proxy_params; }
  location /api/v1/transfers/ { proxy_pass http://payment:8000/api/v1/transfers/; include /etc/nginx/proxy_params; }
  location /api/v1/ledger/ { proxy_pass http://ledger:8000/api/v1/ledger/; include /etc/nginx/proxy_params; }
  location /api/v1/notifications/ { proxy_pass http://notification:8000/api/v1/notifications/; include /etc/nginx/proxy_params; }
  location /api/v1/audit/ { proxy_pass http://audit:8000/api/v1/audit/; include /etc/nginx/proxy_params; }
}
